import Animatedtext from '@/Components/AnimatedText/AnimatedText';
import HireMe from '@/Components/HireMe/HireMe';
import Layout from '@/Components/Layout/Layout';
import TransitionEffect from '@/Components/TransitionEffect/TransitionEffect';
import { ThemeContext } from '@/Context/ThemeContext';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import { useContext } from 'react';

export default function Home() {
  const {theme} = useContext(ThemeContext)

  const CustomLink = ({href, title, className}) => {
    return(
        <Link href={href} className={`${className} relative group`}>
            {title}
            <span className={`h-[1px] inline-block bg-dark absolute left-0 bottom-0.5 group-hover:w-full transition-[width] ease duration-100 }`}></span>
        </Link>
    )
}

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TransitionEffect />
      <main className={`flex items-center ${theme.foreground} w-full min-h-screen`}>
        <Layout className="pt-0 md:p-16 sm:pt-8">
          <div className='flex items-center justify-between w-full lg:flex-col'>
            <div className='w-1/2 md:w-full'>
            <nav className="flex items-center flex-col justify-center">
                <CustomLink href="http://alagzaltest.rf.gd/" title="Algazal Website" className="mr-4 mb-8 text-2xl " />
                <CustomLink href="http://dollartest.great-site.net/" title="Dollar Portfolio Sample" className="mr-4 mb-8 text-2xl " />
                <CustomLink href="http://dollartestp.infinityfreeapp.com/" title="Dollar Portfolio Sample 2" className="mr-4 mb-8 text-2xl " />
                <CustomLink href="/" title="Coming Soon" className="mr-4 mb-8 text-2xl "/>
            </nav>
            </div>
            <div className='w-1/2 flex flex-col items-center self-center text-left lg:w-full lg:!text-center'>
              <Animatedtext text="Osama Namur Web / Game Developer" 
              className="!text-6x1 !text-left xl:!text-5xl lg:!text-center lg:!text-6x1 md:!text-5xl sm:!text-3xl"/>
              <p className='my-4 text-base font-medium md:text-5xl sm:text-3xl'>As a skilled full-stack developer, I am dedicated to turning ideas into innovative web applications. 
Explore my latest projects and articles, showcasing my expertise in React.</p>
              <div className='flex items-center self-center mt-2 lg:self-center'>
                <Link href="/dummy" target={"_blank"} className='flex items-center bg-dark text-light p-2 px-6 rounded-lg text-lg font-semibold hover:bg-light hover:text-dark
                border-2 border-solid border-transparent hover:border-dark md:px-4 md:text-base'>
                
                </Link>
              </div>
            </div>
          </div>
        </Layout>
        <HireMe />
        <section className='absolute right-8 bottom-3 inline-block w-24'>
        </section>
      </main>
    </>
  )
}
//<Image src={procfile} alt="profile pic" className="w-full h-auto lg:hidden md:inline-block md:w-full"/>